Add pychart for v7
Recently faced this error just with `odoo --version`:

    ERROR: openerp 7.0 requires pychart, which is not installed.
    [...]
    pkg_resources.DistributionNotFound: The 'pychart' distribution was not found and is required by openerp